### ISSUE TITLE
 Support null safety

### ISSUE THREAD

**Issue by zs-dima** [anirudhsharma392/Slider-Button#18]
Could be nice to add null safety support for the library to be able to use it with the latest Flutter

**Comment by Shiba-Kar** [comment]
#23

**Comment by hashirshoaeb** [comment]
```yml

  slider_button:
    git: 
      url: https://github.com/Shiba-Kar/Slider-Button.git
      ref: master 
```
